spring.application.name=balbalika-management-system

server.port = 3900

spring.datasource.url= jdbc:mysql://localhost:3306/bapsdelhibalmandal
spring.datasource.username= root
spring.datasource.password= rootuser

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# GCP Bucket
gcp.bucket.name=baps-child-photos
gcp.credentials.path=classpath:gcs-service-account.json
